import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})
const interRegular = localFont({
  src: "./fonts/Inter-Regular.ttf",
  variable: "--font-inter-regular",
  weight: "400",
})
const interSemiBold = localFont({
  src: "./fonts/Inter-SemiBold.ttf",
  variable: "--font-inter-semibold",
  weight: "600",
})
const interBold = localFont({
  src: "./fonts/Inter-Bold.ttf",
  variable: "--font-inter-bold",
  weight: "700",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interRegular.variable} ${interSemiBold.variable} ${interBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
